repos:
# - repo: https://github.com/pre-commit/pre-commit-hooks
#   rev: v2.4.0
#   hooks:
#   - id: flake8
#     args: [--config=.flake8]
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort (python)
