version: '3.8'

services:
  ta2_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ta2_app
    ports:
      - "5000:5000"
    restart: always
    networks:
      - ta2-network

networks:
  ta2-network:
    external: true